"""
Django settings for hrms_portal project.
Generated by 'django-admin startproject' using Django 4.2.
For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import sys

# Apply Python 3.14 compatibility fix
if sys.version_info >= (3, 14):
    try:
        from . import django_py314_fix
    except ImportError:
        pass

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'inbnvhm^mvim%1wcyh^5(xoq)36f^mbv79q*ua#oyglrji%)5b'
DEBUG = True

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
}
#             'format': '{levelname} {message}',
#             'style': '{',
#         },
#         'detailed': {
#             'format': '{asctime} [{name}] {levelname}: {message} - {pathname}:{lineno}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'file': {
#             'level': 'ERROR',
#             'class': 'logging.FileHandler',
#             'filename': BASE_DIR / 'logs' / 'django_errors.log',
#             'formatter': 'detailed',
#         },
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#         'mail_admins': {
#             'level': 'ERROR',
#             'class': 'django.utils.log.AdminEmailHandler',
#             'formatter': 'detailed',
#         },
#         'all_errors': {
#             'level': 'WARNING',
#             'class': 'logging.FileHandler',
#             'filename': BASE_DIR / 'logs' / 'all_errors.log',
#             'formatter': 'detailed',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file', 'console', 'all_errors'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#         'django.request': {
#             'handlers': ['file', 'mail_admins', 'all_errors'],
#             'level': 'ERROR',
#             'propagate': False,
#         },
#         'employees': {
#             'handlers': ['file', 'console', 'all_errors'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#         'salary': {
#             'handlers': ['file', 'console', 'all_errors'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#         'corsheaders': {
#             'handlers': ['file', 'console', 'all_errors'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#         'root': {
#             'handlers': ['file', 'console', 'all_errors'],
#             'level': 'WARNING',
#         },
#     },
# }

# Create logs directory if it doesn't exist
# import os
# os.makedirs(BASE_DIR / 'logs', exist_ok=True)

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'employees',
    'salary',
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hrms_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hrms_portal.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hrmsportalappdev_portal_hrms_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Messages framework
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Authentication settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Session and Cookie Settings
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Custom Admin Styling
ADMIN_TITLE = "HRMS Portal Administration"
ADMIN_HEADER = "HRMS Portal"
ADMIN_INDEX_TITLE = "Welcome to HRMS Portal Administration"

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "HRMS Portal",
    "site_header": "HRMS Portal",
    "site_logo": "images/main-logo.svg",
    "site_icon": "images/favicon.svg",
    "language_chooser": False,
    "search_model": "employees.department",
    "hide_apps": [],
    "hide_models": [],
    "navigation": [
        {"app": "employees", "label": "Employee Management", "icon": "fas fa-users"},
    ],
    "theme": "darkly",
    "custom_css": None,
    "custom_js": None,
    "default_model_parents": True,
    "date_hierarchy": True,
    "show_ui_builder": False,
    "permission_parents": True,
    "raise_404": False,
    "actions": True,
    "changeform_format": "horizontal-tabs",
    "changeform_format_overrides": {},
    "list_per_page": 25,
    "list_show_full_search": True,
    "menu_style": "default",
    "menu_flatten": False,
    "menu_show_all": True,
    "menu_custom_links": [],
    "show_view_as": True,
    "hide_sidebar_toggle": False,
    "navigation_expanded": True,
    "custom_buttons": [],
    "status_colors": {
        "DEFAULT": "#6c757d",
        "SUCCESS": "#28a745",
        "WARNING": "#ffc107",
        "ERROR": "#dc3545",
        "INFO": "#17a2b8",
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '13fff2b7547ed9'
EMAIL_HOST_PASSWORD = 'ddf4b21b3b7140'
DEFAULT_FROM_EMAIL = 'HRMS Portal <hrms@example.com>'
